/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TempTimetableRouteImport } from './routes/temp-timetable'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as AttentionRouteImport } from './routes/attention'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachersIndexRouteImport } from './routes/teachers.index'
import { Route as ClassesIndexRouteImport } from './routes/classes.index'
import { Route as TeachersCodeRouteImport } from './routes/teachers.$code'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as ClassesIdRouteImport } from './routes/classes.$id'
import { Route as SessionClassSubjectRouteImport } from './routes/session.$class.$subject'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TempTimetableRoute = TempTimetableRouteImport.update({
  id: '/temp-timetable',
  path: '/temp-timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const AttentionRoute = AttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersCodeRoute = TeachersCodeRouteImport.update({
  id: '/teachers/$code',
  path: '/teachers/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIdRoute = ClassesIdRouteImport.update({
  id: '/classes/$id',
  path: '/classes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionClassSubjectRoute = SessionClassSubjectRouteImport.update({
  id: '/session/$class/$subject',
  path: '/session/$class/$subject',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attention': typeof AttentionRoute
  '/performance': typeof PerformanceRoute
  '/rankings': typeof RankingsRoute
  '/stats': typeof StatsRoute
  '/temp-timetable': typeof TempTimetableRoute
  '/timetable': typeof TimetableRoute
  '/classes/$id': typeof ClassesIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/teachers/$code': typeof TeachersCodeRoute
  '/classes/': typeof ClassesIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/session/$class/$subject': typeof SessionClassSubjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attention': typeof AttentionRoute
  '/performance': typeof PerformanceRoute
  '/rankings': typeof RankingsRoute
  '/stats': typeof StatsRoute
  '/temp-timetable': typeof TempTimetableRoute
  '/timetable': typeof TimetableRoute
  '/classes/$id': typeof ClassesIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/teachers/$code': typeof TeachersCodeRoute
  '/classes': typeof ClassesIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/session/$class/$subject': typeof SessionClassSubjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attention': typeof AttentionRoute
  '/performance': typeof PerformanceRoute
  '/rankings': typeof RankingsRoute
  '/stats': typeof StatsRoute
  '/temp-timetable': typeof TempTimetableRoute
  '/timetable': typeof TimetableRoute
  '/classes/$id': typeof ClassesIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/teachers/$code': typeof TeachersCodeRoute
  '/classes/': typeof ClassesIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/session/$class/$subject': typeof SessionClassSubjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attention'
    | '/performance'
    | '/rankings'
    | '/stats'
    | '/temp-timetable'
    | '/timetable'
    | '/classes/$id'
    | '/students/$id'
    | '/teachers/$code'
    | '/classes/'
    | '/teachers/'
    | '/session/$class/$subject'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attention'
    | '/performance'
    | '/rankings'
    | '/stats'
    | '/temp-timetable'
    | '/timetable'
    | '/classes/$id'
    | '/students/$id'
    | '/teachers/$code'
    | '/classes'
    | '/teachers'
    | '/session/$class/$subject'
  id:
    | '__root__'
    | '/'
    | '/attention'
    | '/performance'
    | '/rankings'
    | '/stats'
    | '/temp-timetable'
    | '/timetable'
    | '/classes/$id'
    | '/students/$id'
    | '/teachers/$code'
    | '/classes/'
    | '/teachers/'
    | '/session/$class/$subject'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttentionRoute: typeof AttentionRoute
  PerformanceRoute: typeof PerformanceRoute
  RankingsRoute: typeof RankingsRoute
  StatsRoute: typeof StatsRoute
  TempTimetableRoute: typeof TempTimetableRoute
  TimetableRoute: typeof TimetableRoute
  ClassesIdRoute: typeof ClassesIdRoute
  StudentsIdRoute: typeof StudentsIdRoute
  TeachersCodeRoute: typeof TeachersCodeRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
  SessionClassSubjectRoute: typeof SessionClassSubjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temp-timetable': {
      id: '/temp-timetable'
      path: '/temp-timetable'
      fullPath: '/temp-timetable'
      preLoaderRoute: typeof TempTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attention': {
      id: '/attention'
      path: '/attention'
      fullPath: '/attention'
      preLoaderRoute: typeof AttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$code': {
      id: '/teachers/$code'
      path: '/teachers/$code'
      fullPath: '/teachers/$code'
      preLoaderRoute: typeof TeachersCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$id': {
      id: '/classes/$id'
      path: '/classes/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof ClassesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$class/$subject': {
      id: '/session/$class/$subject'
      path: '/session/$class/$subject'
      fullPath: '/session/$class/$subject'
      preLoaderRoute: typeof SessionClassSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttentionRoute: AttentionRoute,
  PerformanceRoute: PerformanceRoute,
  RankingsRoute: RankingsRoute,
  StatsRoute: StatsRoute,
  TempTimetableRoute: TempTimetableRoute,
  TimetableRoute: TimetableRoute,
  ClassesIdRoute: ClassesIdRoute,
  StudentsIdRoute: StudentsIdRoute,
  TeachersCodeRoute: TeachersCodeRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
  SessionClassSubjectRoute: SessionClassSubjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
